### ISSUE TITLE
Error in Mediawiki 1.35

### ISSUE THREAD

**Issue by Patschke** [wikimedia/mediawiki-extensions-MyVariables#2]
I receive an error when attempting to use this extension with Mediawiki 1.35: `Error from line 36 of /usr/share/webapps/mediawiki/extensions/MyVariables/MyVariablesHooks.php: Call to undefined method Parser::disableCache()` (full log below). The extension was working fine on my installation with previous versions of Mediawiki. 

Parser::disableCache() was deprecated in MediaWiki 1.28 and removed in MediaWiki 1.35. 

If you need any additional information feel free to ask. 

```
[81317cf24c10adeb712ab681] /wiki/index.php/Testseite Error from line 36 of /usr/share/webapps/mediawiki/extensions/MyVariables/MyVariablesHooks.php: Call to undefined method Parser::disableCache()

Backtrace:

#0 /usr/share/webapps/mediawiki/includes/HookContainer/HookContainer.php(320): MyVariablesHooks::assignAValue(Parser, array, string, NULL, PPFrame_Hash)
#1 /usr/share/webapps/mediawiki/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#2 /usr/share/webapps/mediawiki/includes/HookContainer/HookRunner.php(2968): MediaWiki\HookContainer\HookContainer->run(string, array)
#3 /usr/share/webapps/mediawiki/includes/parser/Parser.php(2783): MediaWiki\HookContainer\HookRunner->onParserGetVariableValueSwitch(Parser, array, string, NULL, PPFrame_Hash)
#4 /usr/share/webapps/mediawiki/includes/parser/Parser.php(3008): Parser->expandMagicVariable(string, PPFrame_Hash)
#5 /usr/share/webapps/mediawiki/includes/parser/PPFrame_Hash.php(253): Parser->braceSubstitution(array, PPFrame_Hash)
#6 /usr/share/webapps/mediawiki/includes/parser/Parser.php(2887): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#7 /usr/share/webapps/mediawiki/includes/parser/Parser.php(1556): Parser->replaceVariables(string)
#8 /usr/share/webapps/mediawiki/includes/parser/Parser.php(651): Parser->internalParse(string)
#9 /usr/share/webapps/mediawiki/includes/content/WikitextContent.php(374): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#10 /usr/share/webapps/mediawiki/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#11 /usr/share/webapps/mediawiki/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#12 /usr/share/webapps/mediawiki/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#13 /usr/share/webapps/mediawiki/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#14 /usr/share/webapps/mediawiki/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#15 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#16 /usr/share/webapps/mediawiki/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#17 /usr/share/webapps/mediawiki/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#18 /usr/share/webapps/mediawiki/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#19 /usr/share/webapps/mediawiki/includes/page/Article.php(810): PoolCounterWork->execute()
#20 /usr/share/webapps/mediawiki/includes/actions/ViewAction.php(74): Article->view()
#21 /usr/share/webapps/mediawiki/includes/MediaWiki.php(527): ViewAction->show()
#22 /usr/share/webapps/mediawiki/includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
#23 /usr/share/webapps/mediawiki/includes/MediaWiki.php(940): MediaWiki->performRequest()
#24 /usr/share/webapps/mediawiki/includes/MediaWiki.php(543): MediaWiki->main()
#25 /usr/share/webapps/mediawiki/index.php(53): MediaWiki->run()
#26 /usr/share/webapps/mediawiki/index.php(46): wfIndexMain()
#27 {main}
```

**Comment by Patschke** [comment]
My bad. Failed to update - just noticed this as I wanted to create a PR with a fix, and seeing that the changes were already present in the clean fork...
